
# Jekyll config
exclude:
  - CNAME
  - Makefile
  - README.md
future: false
lsi: false
markdown: kramdown
permalink: /:categories/:year/:month/:day/
timezone: Europe/London
plugins:
  - jekyll-paginate

# Pagination
paginate: 7
paginate_path: :num/
